### ISSUE TITLE
Invalid Signatur - get_request_token

### ISSUE THREAD

**Issue by SeverinWeber** [tripit/python_binding_v1#2]
When i try to use get_request_token.py with valid apikey and secret i get 
<Response><Error><code>401</code><detailed_error_code>104.100000</detailed_error_code><description>invalid signature</description></Error></Response>

what is wrong?

**Comment by tariqislam** [comment]
Hi SeverinWeber,

We don't answer issues in this section of our Github, could you please post this question on our TripIt API issues page: https://github.com/tripit/api/issues

Also, please include the following log information for us to help debug:
- When API call was made
- Complete details of API call
  - consumer key, and any other tokens used for OAuth (except api secret)
  - API endpoint hit
  - API payload
  - HTTP Request/Response headers
  - Complete reply from our server

Thanks!

Tariq
