### ISSUE TITLE
Missing required authorized token for OAuthConsumerCredential

### ISSUE THREAD

**Issue by nearodney** [tripit/python_binding_v1#3]
Regarding OAuth Consumer Credential, _not_ WebAuthCredential, the sample code in the readme shows hardcoded string values for all keys. After TripIt generates the consumer_key and secret, we need an example or comment on the authorized_token_key and secret. There are no explanations for obtaining our authorized_token strings once we have our own consumer keys for our application generated by the TripIt API website.

**Comment by vsejpal** [comment]
Hi @nearodney. Thanks for reaching out.

I will attempt to explain the end-to-end "oauth-dance" (using the python binding) below. I believe it is the `Authorize the request token` section, you are looking for. 


**Get a request token**
_Request_

```
$ python get_request_token.py https://api.tripit.com 40f9e72c1a0a587225b9c0b34765ca2989d156df <consumer_secret>
```

_Response_

```
{'oauth_token_secret': '<token_secret>', 'oauth_token': 'adb5d9d2fd95ee4ebf04fc9fce21a8cfacaa1b04'}
```

**Authorize the request token**

Take your web-browser to `https://www.tripit.com/oauth/authorize?oauth_token=<oauth_token>&oauth_callback=<oauth_callback>`

_Note about `<oauth_token>`: This is `adb5d9d2fd95ee4ebf04fc9fce21a8cfacaa1b04` obtained in previous step_

_Note about `<oauth_callback>`: This is the callback URL that TripIt will use upon successful access token authorization. This parameter is optional if you associated a URL with your application when you registered it and obtained your OAuth consumer key and secret. If you supplied a URL when you registered the application, providing this request parameter will override that value.

**Generate the access_token and token_secret**
_Request_

```
$ python get_authorized_token.py https://api.tripit.com 40f9e72c1a0a587225b9c0b34765ca2989d156df <consumer_secret> adb5d9d2fd95ee4ebf04fc9fce21a8cfacaa1b04 <token_secret>
```

_Response_

```
{'oauth_token_secret': '<authorized_token_secret>', 'oauth_token': '6959101cd76fbaca8a4032be2f9a5c50975045a4'}
```

Keep this access_token / token_secret pair safe somewhere in your config file or DB

Finally, you can call our API
<img width="1176" alt="screen shot 2016-05-31 at 4 04 33 pm" src="https://cloud.githubusercontent.com/assets/5566340/15693398/cdfe0878-2749-11e6-859d-a0c698fed551.png">


Hopefully, that helps.
